### ISSUE TITLE
Read services from story.yaml

### ISSUE THREAD

**Issue by wilzbach** [storyscript/hub-sdk-python#38]
tl;dr: `story.yaml` already exists and should be checked by the SDK.

See also: https://github.com/storyscript/hub-sdk-python/issues/27

**Comment by adnrs96** [comment]
what is going to be the format of this local `alias` ?

**Comment by wilzbach** [comment]
Format should be:

```yaml
services:
    jean/http:
      version: 0.1.0
      alias: foo
```
